# -*- coding: utf-8 -*-
{
    "name": "Sistema Terrenos / Land",
    "summary": "Land",
    "description": """ Land""",
    "author": "Jzolutions",
    "category": "Uncategorized",
    "version": "17.0",
    "depends": ["sale_management"],
    "data": [
        "security/group.xml",
        "security/ir.model.access.csv",
        "security/ir_rules.xml",
        "views/product_attribute_view_form.xml",
        "views/product_template_form_view.xml",
        "views/account_move.xml",
        "views/sale_order.xml",
        "wizard/import_bancarios.xml",

        #"views/report_invoice_document.xml",
        #'wizard/view_sale_advance_payment_inv.xml',
        "views/seller_land.xml",
        "views/commission_land.xml",
        "views/crm_team_view_form.xml",
        "data/sequence.xml",
        "data/cron.xml",
        "views/report_dues_land.xml",
        'views/product_template_attribute_value.xml',
        "views/report_lot_land.xml",
        'report/report_lot.xml',
        'report/report_schedule.xml',
        'report/report_resueltos.xml',
        #'views/account_journal.xml',
        "report/report_sale.xml",

    ],
    # 'uninstall_hook': 'uninstall_hook',
    #"external_dependencies": {"python": ["msal"]},
    "application": True,
    "installable": True,
    "auto_install": False,

}
