from . import product_attribute
from . import sale_order
from . import sale_order_line
#from . import variant
from . import product_template
from . import product_product
from . import account_move
from . import account_journal
from . import sale_order
from . import seller_land
from . import schedule_dues_land
from . import commission_land
from . import crm_team
from . import account_move_line
from . import report_dues_land