# -*- coding: utf-8 -*-
{
    'name': "Personalizaciones para Anka",
    'summary': "Personalizaciones para Anka",
    'description': "Personalizaciones para Anka",
    'author': "Oxe360",
    'license': "OPL-1",
    'website': "http://www.oxe360.com",
    'category': 'Accounting/Accounting',
    'version': '17.20250604',
    'depends': [
        'contacts',
        'l10n_pe',
        'account',
        # 'account_accountant',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/account_followup_data.xml',
        'views/res_config_settings_views.xml',
        'wizard/followup_manual_reminder_operation_view.xml',
        'wizard/followup_manual_reminder_debtor_view.xml',
        'views/res_partner_views.xml',
        'views/operaciones_views.xml',
        'views/operacion_contrato_views.xml',
        'views/operacion_documento_views.xml',
        'views/operacion_liquidacion_views.xml',
        'views/operacion_tipo_views.xml',
        'views/operacion_operacion_views.xml',
        'wizard/file_upload_operation_view.xml',
        'wizard/liquidacion_payment_register_view.xml',
        'report/report_liquidacion.xml',
        'report/report_menu.xml',
        
    ],
    'license': "OPL-1",
}
