{
    "name": "Phone Calls",
    "author": "Nians",
    'website': 'https://nians.com/odoo',
    "support": "support@technians.com",
    'version': '19.0.1.0.0',
    "category": "CRM",
    "summary": """ Calls Feature & Auto-format phone number """,
    "description": """ Added Similar Calls Feature & Auto-format phone number """,
    "depends": ['base', 'mail','crm'],
    "data": [
        'security/ir.model.access.csv',
        'security/calls_user_groups.xml',
        'data/call_sequence.xml',
        'views/calls_views.xml',
        'views/res_config_settings.xml',
    ],
    'images': ['static/description/banner.jpg'],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
