from . import place_event
from . import sale_order
from . import crm_lead
from . import stock_picking
from . import product
from . import planning_role
from . import res_partner
from . import payments_sale_order
from . import account_move